version: '3'

services:
  express_backend:
    container_name: express_backend
    build: ./express
    ports:
      - "80:80"
    restart: always
    networks:
       - webappnetwork

  react_frontend:
    container_name: react_frontend
    build: ./client
    ports:
      - "3000:3000"
    restart: always
    networks:
       - webappnetwork

networks:
    webappnetwork:
        driver: bridge
