version: '3'
services:

  dronuts-2019-group-4:
    container_name: dronuts-2019-group-4
    build: ./
    ports:
      - target: 80
        published: 3000
        protocol: tcp
        mode: host
    restart: always
